[package]
name = "game"
version = "0.1.0"
authors = ["Cameron Clough <cameronjclough@gmail.com>"]
edition = "2018"

[dependencies]
gl = { path = "lib/gl" }

[dependencies.sdl2]
version = "0.32.2"
features = ["bundled", "static-link"]
